site_name: MongoX
site_description: Python MongoDB Object-Document-Mapper based on Motor and Pydantic

theme:
    name: 'material'
    palette:
      primary: white
    logo: assets/images/icon.png
    favicon: assets/images/icon.png

repo_name: aminalaee/mongox
repo_url: https://github.com/aminalaee/mongox

nav:
    - Quickstart: 'index.md'
    - Usage:
      - Defining documents: 'defining_documents.md'
      - Working with documents: 'queriying_documents.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-7Z9QW7E0WL
